services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-api-app
    ports:
      - "8099:8099"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - red-app

networks:
  red-app:
    external: true
    
